language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.15.0

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --features "serde"
  - cargo test --verbose --features "serde"

notifications:
  email:
    on_success: never
