language: rust
rust:
  - 1.16.0
  - 1.17.0
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - 1.21.0
  - 1.22.0
  - 1.23.0
  - 1.24.0

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --features "serde"
  - cargo test --verbose --features "serde"

notifications:
  email:
    on_success: never
