language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.10.0
  - 1.11.0
  - 1.12.0
  - 1.13.0
  - 1.14.0
  - 1.15.0
  - 1.16.0
  - 1.17.0

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
